# This file was auto-generated. Do not edit.

using module "./4.1/AccountsApiClient.psm1"
using module "./4.1/BuildApiClient.psm1"
using module "./4.1/CoreApiClient.psm1"
using module "./4.1/DashboardApiClient.psm1"
using module "./4.1/ExtensionManagementApiClient.psm1"
using module "./4.1/GitApiClient.psm1"
using module "./4.1/GraphApiClient.psm1"
using module "./4.1/MemberEntitlementManagementApiClient.psm1"
using module "./4.1/NotificationApiClient.psm1"
using module "./4.1/OperationsApiClient.psm1"
using module "./4.1/PolicyApiClient.psm1"
using module "./4.1/ProfileApiClient.psm1"
using module "./4.1/ReleaseApiClient.psm1"
using module "./4.1/SearchApiClient.psm1"
using module "./4.1/SecurityApiClient.psm1"
using module "./4.1/ServiceEndpointApiClient.psm1"
using module "./4.1/ServiceHooksApiClient.psm1"
using module "./4.1/SymbolApiClient.psm1"
using module "./4.1/TaskAgentApiClient.psm1"
using module "./4.1/TfvcApiClient.psm1"
using module "./4.1/WikiApiClient.psm1"
using module "./4.1/WorkApiClient.psm1"
using module "./4.1/WorkItemTrackingApiClient.psm1"
using module "./4.1/WorkItemTrackingProcessApiClient.psm1"
using module "./4.1/WorkItemTrackingProcessDefinitionsApiClient.psm1"
using module "./4.1/WorkItemTrackingProcessTemplateApiClient.psm1"

