# This file was auto-generated. Do not edit.

using module "./azure-devops-server-7.1/BuildOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/CoreOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/DashboardOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/ExtensionManagementOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/FavoriteOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/FeedOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/GitOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/IdentitiesOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/MavenOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/NotificationOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/NpmOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/NuGetOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/OperationsOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/PipelinePermissionsOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/PipelinesapprovalOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/PipelinesChecksOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/PipelinesOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/PolicyOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/ReleaseOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/SearchOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/SecurityOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/SecurityRolesOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/ServiceEndpointOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/ServiceHooksOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TaskAgentOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TaskOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TestOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TestPlanOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TestResultsOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/TfvcOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/WikiOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/WorkItemTrackingOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/WorkItemTrackingProcessOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/WorkItemTrackingProcessTemplateOnpremApiClient.psm1"
using module "./azure-devops-server-7.1/WorkOnpremApiClient.psm1"

