# This file was auto generated. Do not edit.

using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/BuildOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/CoreOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/DashboardOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/ExtensionManagementOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/FeedOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/GitOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/IdentitiesOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/MavenOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/NotificationOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/NpmOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/NuGetOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/OperationsOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/PipelinePermissionsOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/PipelinesapprovalOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/PipelinesChecksOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/PipelinesOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/PolicyOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/ReleaseOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/SearchOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/SecurityOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/SecurityRolesOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/ServiceEndpointOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/ServiceHooksOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/TaskAgentOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/TestOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/TestPlanOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/TestResultsOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/TfvcOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/WikiOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/WorkItemTrackingOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/WorkItemTrackingProcessOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/WorkItemTrackingProcessTemplateOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/azure-devops-server-7.0/WorkOnpremApiClient.psm1"

