# This file was auto generated. Do not edit.

using module "./azure-devops-toolbox/api_clients/tfs-4.1/BuildOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/CoreOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/DashboardOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/ExtensionManagementOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/GitOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/NotificationOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/OperationsOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/PolicyOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/ReleaseOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/SearchOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/SecurityOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/ServiceEndpointOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/ServiceHooksOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/TaskAgentOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/TfvcOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WikiOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WorkItemTrackingOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WorkItemTrackingProcessDefinitionsOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WorkItemTrackingProcessOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WorkItemTrackingProcessTemplateOnpremApiClient.psm1"
using module "./azure-devops-toolbox/api_clients/tfs-4.1/WorkOnpremApiClient.psm1"

